config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :chats
  devise_for :users
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy"
    post "session/user", to: "devise/sessions#create"
  end

  # mount Sidekiq::Web => '/sidekiq'
  resources :retailers
  resources :carts
  resources :orders
  resources :addresses
  resources :shoppers
  resources :subcategories
  resources :categories
  resources :brands
  resources :companies
  resources :session
  resources :products do
    collection do
      get :search
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #FOR API CALLS 
  namespace :api do
  end
  # Defines the root path route ("/")
  get '/' => 'users#index' 

  post'/sessions' => 'xyz#index'

  mount API::Base => '/'
  
  mount ActionCable.server => '/cable'
  
  #Grapes ROUTES
  # mount Eshop::Base => '/api'
  #mount Eshop::Base => '/api'
  # get '/API/V1/products' => 'API/V1/products'
end

app/models/retailer.rb
class Retailer < ApplicationRecord
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  # before_action :require_user
  before_action :set_retailer, only: %i[ show edit update destroy ]

  # GET /retailers or /retailers.json
  def index
    @retailers = Retailer.all
  end

  # GET /retailers/1 or /retailers/1.json
  def show
    # client = Ignite::Client.new
    # @categories = client.query("SELECT * FROM CATEGORIES")
    @categories = Category.all
    @cart = Cart.where(shopper_id: Redis.current.get("shopper_id"))
    if(@cart[0] == nil)
      @prods = "Cart is empty"
    else
      @prods = ActiveSupport::JSON.decode("#{@cart[0].products.to_json}")
    end
    @ordersPending = Order.where(shopper_address: Redis.current.get("address"), status: '0')
    @ordersCompleted = Order.where(shopper_address: Redis.current.get("address"), status: '1')
  end

  # GET /retailers/new
  def new
    @retailer = Retailer.new
  end

  # GET /retailers/1/edit
  def edit
  end

  # POST /retailers or /retailers.json
  def create
    @retailer = Retailer.new(retailer_params)

    respond_to do |format|
      if @retailer.save
        format.html { redirect_to retailer_url(@retailer), notice: "Retailer was successfully created." }
        format.json { render :show, status: :created, location: @retailer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retailers/1 or /retailers/1.json
  def update
    respond_to do |format|
      if @retailer.update(retailer_params)
        format.html { redirect_to retailer_url(@retailer), notice: "Retailer was successfully updated." }
        format.json { render :show, status: :ok, location: @retailer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retailers/1 or /retailers/1.json
  def destroy
    @retailer.destroy

    respond_to do |format|
      format.html { redirect_to retailers_url, notice: "Retailer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retailer
      @retailer = Retailer.find(params[:id])
      Redis.current.set("retailer_id","#{@retailer.id}")
      puts "============== REDIS SAVED RETAILER ID: #{@retailer.id} ==============="
      @categories = Category.all
      @cart = Cart.where(shopper_id: Redis.current.get("shopper_id"))
      if(@cart[0] == nil)
        @prods = "Cart is empty"
      else
        @prods = ActiveSupport::JSON.decode("#{@cart[0].products.to_json}")
      end
      @ordersPending = Order.where(shopper_address: Redis.current.get("address"), status: '0')
      @ordersCompleted = Order.where(shopper_address: Redis.current.get("address"), status: '1')
    end
    # Only allow a list of trusted parameters through.
    def retailer_params
      params.require(:retailer).permit(:name, :email, :pass, :phone, :address)
    end
end

app/views/retailers/_form.html.erb
<%= form_with(model: retailer) do |form| %>
  <% if retailer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
        <% retailer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :pass, style: "display: block" %>
    <%= form.text_field :pass %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_area :phone %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/retailers/_retailer.html.erb
<div id="<%= dom_id retailer %>">
  <p>
    <strong>Name:</strong>
    <%= retailer.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= retailer.email %>
  </p>

  <p>
    <strong>Pass:</strong>
    <%= retailer.pass %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= retailer.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= retailer.address %>
  </p>

</div>

app/views/retailers/edit.html.erb
<h1>Editing retailer</h1>

<%= render "form", retailer: @retailer %>

<br>

<div>
  <%= link_to "Show this retailer", @retailer %> |
  <%= link_to "Back to retailers", retailers_path %>
</div>

app/views/retailers/index.html.erb
<p style="color: green"><%= notice %></p>
<div>
   <%= link_to "Logout", "/" %>
</div>
<h2>Retailers</h2> 
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th>email</th>
    <th></th>
  </tr>
<% @retailers.each do |retailer| %>
  <tr>
    <td><%= retailer.name %></td>
    <td><%= retailer.address %></td>
    <td></td>
    <td><%= retailer.email %></td>
    <td><%= link_to 'Select', retailer %></td>
  </tr>
<% end %>
</table>
<br />
<hr>
<hr>
<h3>Pending Orders</h3> 
<table>
  <tr>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @orders.each do |order| %>
  <tr>
    <td><%= order.status %></td>
    <td><%= link_to 'Update Order', edit_order_path(order) %></td>
  </tr>
<% end %>
</table>
<br />

app/views/retailers/new.html.erb
<h1>New retailer</h1>

<%= render "form", retailer: @retailer %>

<br>

<div>
  <%= link_to "Back to retailers", retailers_path %>
</div>

app/views/retailers/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= link_to "Change Address", addresses_path %>
  <%= link_to "Logout", "/" %>
</div>
<hr>
<h2>Categories</h2> 
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Select', category %></td>
  </tr>
<% end %>
</table>
<br />
<hr>
<h3>Current Cart</h3> 
<% if @prods == "Cart is empty" %>
<p>Cart is empty</p>
<% else %>
<table>
  <tr>
    <th></th>
    <th>Total Quantity</th>
    <th></th>
    <th></th>
    <th>Total-Price</th>
    <th></th>
  </tr>
<% @cart.each do |cartItems| %>
  <tr>
    <td></td>
    <td>
    &nbsp;&nbsp;&nbsp; <%=cartItems.qty%><br>
    </td>
    <td></td>
    <td></td>
    <td>
    <%= cartItems.total%> Pkr<br>
    </td> 
    <td>
    <%# <%= @cart[0]["ITEMS"]%><br> 
    </td>
  </tr>
<% end %>
</table>
<% @cart[0].products.each do |product| %><br>
<tr>
<td>Name</td>
</tr>
<tr>
<td><%= product["product_name"] %></td>
</tr>
<% end%>
<br>
<%= link_to "Place Order", new_order_path %>
<% end %>

<hr>
<h3>Pending Orders</h3> 
<table>
<h5>Products</h5>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @ordersPending.each do |orderP| %>
  <tr>
    <td>
    <% orderP.status %>
    </td>
  </tr>
<% end %>
</table>
<hr>
<h5>Completed Orders</h3> 
<h5>Products</h5>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @ordersCompleted.each do |orderP| %>
  <tr>
    <td>
    <% orderP.status %>
    </td>
  </tr>
<% end %>
</table>
<br />