config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :chats
  devise_for :users
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy"
    post "session/user", to: "devise/sessions#create"
  end

  # mount Sidekiq::Web => '/sidekiq'
  resources :retailers
  resources :carts
  resources :orders
  resources :addresses
  resources :shoppers
  resources :subcategories
  resources :categories
  resources :brands
  resources :companies
  resources :session
  resources :products do
    collection do
      get :search
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #FOR API CALLS 
  namespace :api do
  end
  # Defines the root path route ("/")
  get '/' => 'users#index' 

  post'/sessions' => 'xyz#index'

  mount API::Base => '/'
  
  mount ActionCable.server => '/cable'
  
  #Grapes ROUTES
  # mount Eshop::Base => '/api'
  #mount Eshop::Base => '/api'
  # get '/API/V1/products' => 'API/V1/products'
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/controllers/api/v1/chats.rb
module API
    module V1
      class Chats < Grape::API
          version 'v1', using: :path
          format :json
          prefix :api
          resource :chats do
            desc 'Return all Chats'

            #GET ALL CHATS
            get :GetAll do 
                Chat.all
            end

            #DELETE ANY CHAT
            delete do
              Chat.where(id: params[:id]).delete
              return "Chats Deleted"
            end

          end
      end
    end
  end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /chats or /chats.json
  def index
    @chats = Chat.all.pluck(:message)
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chats = Chat.all.pluck(:message)
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)
    respond_to do |format|
      if @chat.save
        ActionCable.server.broadcast('room_channel', {body: "#{@chat}"}) 
        # format.html { redirect_to chat_url(@chat), notice: "Chat was successfully created." }
        # format.json { render :show, status: :created, location: @chat }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:message)
    end
end

app/views/chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Message:</strong>
    <%= chat.message %>
  </p>

</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat, remote: true) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>
<br>
<div>
  <%= link_to "Home", addresses_path %>
   <%= link_to "Logout", "/" %>
</div>
<br><hr>
<h1>All Messages</h1>
<div id="chats">
  <% @chats.each do |chat| %>
    - <%= chat %><br>
    <!--<p>
      <%= link_to "Show this chat", chat %>
    </p> -->
  <% end %>
</div>
<br><hr>
<%= link_to "New chat", new_chat_path %>

app/views/chats/new.html.erb
<br><br>
<div>
  <%= link_to "Home", addresses_path %>
   <%= link_to "Logout", "/" %>
</div>
<br>
<hr>
<h1>New chat</h1>
<%= render "form", chat: @chat %>
<br>
<hr>
<h3>RECENT CHATS</h3>
<% @chats.each do |chat| %>
<p><%= chat %></p>
<% end %>
<div id="new_message"%></div>
<br>

<!--<div>
  <%= link_to "Back to chats", chats_path %>
</div>-->

app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @chat %>
<div>
  <%= link_to "Edit this chat", edit_chat_path(@chat) %> |
  <%= link_to "Back to chats", chats_path %>

  <%= button_to "Destroy this chat", @chat, method: :delete %>
</div>