config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :chats
  devise_for :users
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy"
    post "session/user", to: "devise/sessions#create"
  end

  # mount Sidekiq::Web => '/sidekiq'
  resources :retailers
  resources :carts
  resources :orders
  resources :addresses
  resources :shoppers
  resources :subcategories
  resources :categories
  resources :brands
  resources :companies
  resources :session
  resources :products do
    collection do
      get :search
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #FOR API CALLS 
  namespace :api do
  end
  # Defines the root path route ("/")
  get '/' => 'users#index' 

  post'/sessions' => 'xyz#index'

  mount API::Base => '/'
  
  mount ActionCable.server => '/cable'
  
  #Grapes ROUTES
  # mount Eshop::Base => '/api'
  #mount Eshop::Base => '/api'
  # get '/API/V1/products' => 'API/V1/products'
end

app/models/brand.rb
class Brand < ApplicationRecord
    # validates :name, :presence => true,uniqueness: true
    # validates :slogan, :presence => true,uniqueness: true
    belongs_to :company
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # before_action :require_user
  before_action :set_brand, only: %i[ show edit update destroy ]
  # GET /brands or /brands.json
  def index
    # postsavg= Post.all.average(:rate).to_i
    #  @posts=Post.all#.where(:rate => postsavg)
    @brands = Brand.where(company_id: Redis.current.get("company_id"))
  end
  # GET /brands/1 or /brands/1.json
  def show
    @brand = Brand.find(params[:id])
  end
  # GET /brands/new
  def new 
    @brand = Brand.new
  end
  # GET /brands/1/edit
  def edit
  end
  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)
    # @brand[:company_id] = 99
    @brand.company_id = Redis.current.get("company_id")
    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand = Brand.where(company_id: Redis.current.get("company_id"))
    $i = 0;
    while @brand[$i] != nil
      $t_id = @brand[$i].id.to_i
      Product.where(brand_id: $t_id).destroy_all
      $i +=1;
    end
    Brand.where(company_id: Redis.current.get("company_id")).destroy_all
    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
      Redis.current.set("brand_id","#{@brand.id}")
      @product = Product.where(brand_id: Redis.current.get("brand_id"))
    end
    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :slogan)
    end
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
  <p>
    <strong>Name:</strong>
    <%= brand.name %>
  </p>

  <p>
    <strong>Slogan:</strong>
    <%= brand.slogan %>
  </p>

</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :slogan, style: "display: block" %>
    <%= form.text_area :slogan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Show this brand", @brand %> |
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/index.html.erb
<div>
   <%= link_to "Logout", "/" %>
</div>
<h1>Listing Brands</h1> 
<table>
  <tr>
    <th>Name</th>
    <th>Slogan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.name %></td>
    <td><%= brand.slogan %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Delete', brand, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to "New brand", new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= link_to "Home", brands_path %>
   <%= link_to "Logout", "/" %>
</div>
<h2>Brand</h2>
<%= render @brand %>
<%= link_to "Edit this brand", edit_brand_path(@brand) %> |
<%= link_to "Back to brands", brands_path %>
<%= button_to "Destroy this brand", @brand, method: :delete %>
<hr>
<h3><%= @brand.name %> Products:</h3> 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th>Quantity</th>
  </tr>
<% @product.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>  
    <td></td>
    <td><%= product.quantity %></td>
    <td><%= link_to "Edit ", edit_product_path(product.id) %></td>
    
  </tr>
<% end %>
</table>
<hr>
<p>
   <%= link_to 'Search', search_products_path %> Product.
</p>
<%= link_to 'New product', new_product_path %>