config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :chats
  devise_for :users
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy"
    post "session/user", to: "devise/sessions#create"
  end

  # mount Sidekiq::Web => '/sidekiq'
  resources :retailers
  resources :carts
  resources :orders
  resources :addresses
  resources :shoppers
  resources :subcategories
  resources :categories
  resources :brands
  resources :companies
  resources :session
  resources :products do
    collection do
      get :search
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #FOR API CALLS 
  namespace :api do
  end
  # Defines the root path route ("/")
  get '/' => 'users#index' 

  post'/sessions' => 'xyz#index'

  mount API::Base => '/'
  
  mount ActionCable.server => '/cable'
  
  #Grapes ROUTES
  # mount Eshop::Base => '/api'
  #mount Eshop::Base => '/api'
  # get '/API/V1/products' => 'API/V1/products'
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
    include Searchable
    # def self.import_csv!
    #     filepath = "/Users/umarmahmoodshk/products_202207281740.csv"
    #     res = CSV.parse(File.read(filepath), headers: true)
    #     res.each_with_index do |s ,ind|
    #         Product.create!(
    #             name: s["name"],
    #             price: s["price"],
    #             description: s["description"],
    #         )
    #     end
    # end


    # validates :name, :presence => true,uniqueness: true
    # validates :price, :presence => true
    # validates :description, :presence=> true
    belongs_to :brand
end

app/controllers/api/v1/products.rb
module API
    module V1
      class Products < Grape::API
          version 'v1', using: :path
          format :json
          prefix :api
          resource :products do
            desc 'Return all Products'
            
            #GET ALL PRODUCTS
            get do
              product = Product.all
              if product == []
                return "No product added yet"
              else
                return product
              end
            end

            #GET ALL PRODUCTS OF A CERTAIN BRAND
            get :BrandProduct do
              product = Product.where(brand_id: params[:brand_id])
              if product == []
                return "Product Not Found with given Brand"
              else
                return product
              end
            end

            #GET ALL PRODUCTS OF A CERTAIN SUB-CATEGORY
            get :SubCategoryProduct do
              product = Product.where(subcategory_id: params[:subcategory_id])
              if product == []
                return "Product Not Found with given SubCategory"
              else
                return product
              end
            end
            
            get :IgniteProduct do
              client = Ignite::Client.new(username: " username ", password: " password ",host:" host url ",port:"10800")
              @products = client.query("SELECT * FROM PRODUCTS")
              return @products
            end
            

            #CREATES A NEW PRODUCT 
            get :PostgresCreateProduct do
                product = Product.new(
                    name: "FaKe",
                    price: 99, 
                    description: "Fake",
                    brand_id: 9,  
                    quantity: 99,  
                    availability: true,  
                    subcategory_id: 99,
                )
                @products = Product.all
                if product.save
                    return @products
                else
                    return "Somethig Went Wrong due to wrong or empty params"
                end
            end
            get :IgniteCreateProduct do
              client = Ignite::Client.new(username: " username ", password: " password ",host:" host url ",port:"10800")
              $i = client.query("SELECT COUNT(ID) FROM PRODUCTS")
              client.query("INSERT INTO PUBLIC.PRODUCTS(ID, NAME, PRICE, SUBCATEGORY_ID, BRAND_ID, QUANTITY, DESCRIPTION)VALUES(#{$i[0]["COUNT(ID)"]+1}, '#{Faker::Commerce.product_name}', #{99}, #{49}, #{9}, 100, '#{Faker::Commerce.department(2, true)}')")
              @products = client.query("SELECT * FROM PRODUCTS")# WHERE ID = #{$id}")
              return @products
            end

            #GET ALL PRODUCTS WHICH ARE AVAILABLE
            get :AvailableProduct do
              product = Product.where(availability: true)
              if product == []
                return "No Product is available currently"
              else
                return product
              end
            end

            #GET ALL PRODUCTS WHICH ARE UNAVAILABLE
            get :UnAvailableProduct do
              product = Product.where(availability: false)
              if product == []
                return "No Product is available currently"
              else
                return product
              end
            end

            #UPDATE PRODUCT QUANTITY
            put :UpdateProduct do
              product = Product.find(params[:id])
              if product == nil
                return "No Product is available "
              else
                product.update(
                    name: params[:name],
                    price: params[:price], 
                    description: params[:description],
                    brand_id: params[:brand_id],  
                    quantity: params[:quantity],  
                    availability: params[:availability],  
                    subcategory_id: params[:subcategory_id],
                )
                return product
              end
            end

            #CREATES A NEW PRODUCT 
            post :CreateProduct do
                product = Product.new(
                    name: params[:name],
                    price: params[:price], 
                    description: params[:description],
                    brand_id: params[:brand_id],  
                    quantity: params[:quantity],  
                    availability: params[:availability],  
                    subcategory_id: params[:subcategory_id],
                )
                if product.save
                    return "New Product Added"
                else
                    return "Somethig Went Wrong due to wrong or empty params"
                end
            end

            #DELETE ANY PRODUCT OF ANY BRAND
            delete do
              Product.find(params[:id]).delete
              return "Product Deleted"
            end

          end
      end
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :require_user
  # before_action :set_product, only: %i[ show edit update destroy ]
  # GET companies/id?/products or /companies/id?/products.json
 def search
  query = params[:search_products].presence && params[:search_products][:query]

if query
  @products = Product.search_published(query)
end
 end
 
  def index

  #  @brand = Brand.where(company_id: Redis.current.get("company_id"))
  #  @products = Product.all
  client = Ignite::Client.new(username: " username ", password: " password ",host:" hosted url ",port:"10800")
  cache = client.get_or_create_cache("test")
  $i = client.query("SELECT COUNT(ID) FROM PRODUCTS")
  client.query("INSERT INTO PUBLIC.PRODUCTS(ID, NAME, PRICE, SUBCATEGORY_ID, BRAND_ID, QUANTITY, DESCRIPTION)VALUES(#{$i[0]["COUNT(ID)"]+1}, '#{Faker::Commerce.product_name}', #{Faker::Number.between(1, 100)}, #{Faker::Number.between(8, 50)}, #{Faker::Number.between(6, 10)}, 100, '#{Faker::Commerce.department(2, true)}')")
  # @prod = Product.new( name:"FAKE", price: 99,brand_id: 51,subcategory_id: 11, availability: 100,description: "FAKE DEP")
  # @prod.save
  # @products = Product.all

  @products = client.query("SELECT * FROM PRODUCTS")
   respond_to do |format|
       format.html  # index.html.erb
       format.json  { render :json => @products }
   end
  end
  # GET /companies/id?/products/1 or /companies/id?/products/1.json
  def show
    storage = Google::Cloud::Storage.new(
       project_id: " ID",
       credentials: "../keyfile.json"
     )
    
    bucket = storage.bucket " BUCKET NAME "
      @product = Product.find(params[:id])
      if (file = bucket.file "#{@product.id}.jpg")
        @url = " firebase url "
      else
        @url = " firebase url "
      end
  end
  def new
      @product = Product.new
      puts "#{@product}"
      respond_to do |format|
        format.html  # new.html.erb
        format.json  { render :json => @product }
      end
  end
  # POST /products/new
  def create
      @product = Product.new(product_params)
      # @product[:brand_id] = 99
      @product.brand_id =  Redis.current.get("brand_id")
      $val = @product.availability
      # @product.availability = $val.to_b
      respond_to do |format|
          if @product.save
            file_data = product_params_image[:image].tempfile.path
    storage = Google::Cloud::Storage.new(
       project_id: " ID ",
       credentials: "../keyfile.json"
     )
    
    bucket = storage.bucket " BUCKET NAME "
    file = bucket.create_file file_data , "#{@product.id}.jpg"
              format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
              format.json { render :show, status: :created, location: @product }
          else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @product.errors, status: :unprocessable_entity }
          end

         
      end
    end

    # GET /companies/id?/products/1/edit
def edit
  @product = Product.find(params[:id])
end
# PATCH/PUT /companies/id?/products/1 or /companies/id?/products/1.json
def update
  if(Redis.current.get("shopper_id") == nil)
    puts"-==========COMPANY IS LOGGED IN =============-"
    respond_to do |format|
      if @product.update(product_params)
        file_data = product_params_image[:image].tempfile.path
        storage = Google::Cloud::Storage.new(
          project_id: " ID",
          credentials: "../keyfile.json"
        )
        bucket = storage.bucket " BUCKER NAME "
        file = bucket.create_file file_data , "#{@product.id}.jpg"
        format.html { redirect_to product_url(@product), notice: "Product was updated successfully." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
      return 
    end
  else
  puts"-~~~~~~~~~~~~~~~~~~~~~ USER IS LOGGED IN #{Redis.current.get("shopper_id")} -~~~~~~~~~~~~~~~~~~~~~"
    prod_qty=product_params[:quantity]
    # @cart = Cart.where(shopper_id: Redis.current.get("shopper_id")).first
    client = Ignite::Client.new
    count = client.query("SELECT COUNT(ID) FROM CARTS")
    $ID = count[0]["COUNT(ID)"] + 1
    # @product = Product.find(params[:id])  
    @product = client.query("SELECT * FROM PRODUCTS WHERE ID = #{params[:id]}")
    $cart_total = @product[0]["PRICE"] * prod_qty.to_i
    Redis.current.set("cart_#{$ID}_total","#{$cart_total}")
    Redis.current.set("cart_id","#{$ID}")
    client.query("INSERT INTO PUBLIC.CARTS(ID, TOTAL, SHOPPER_ID, QTY, ORDER_ID, PRODUCT_NAME, PRODUCT_PRICE)VALUES(#{$ID}, #{$cart_total}, #{Redis.current.get("shopper_id")},#{prod_qty.to_i},0, '#{@product[0]["NAME"]}', #{@product[0]["PRICE"].to_i})")
    # @cart = client.query("SELECT * FROM CARTS WHERE SHOPPER_ID = #{Redis.current.get("shopper_id")}")
    # if (@cart == [])
      # puts "Cart not found creating New cart"  
      # @cart.qty += prod_qty.to_i  
      # @cart.shopper_id= Redis.current.get("shopper_id")
      # prod = {
      #     "product_id" : "#{@product.id}",
      #     "product_name" : "#{@product.name}",
      #     "product_qty" : "#{prod_qty.to_i}",  
      #     "product_total" : "#{@product.price * prod_qty.to_i}",  
      #     "retailer_id" => "#{Redis.current.get("retailer_id")}",  
      #     "status" => "false"  
      # }
      # @cart.products = prod
      # @cart.save  
      # puts "-=========PRODUCT IN CART AS: #{prod}==========-"
      # respond_to do |format|  
      #   if @cart.save  
      #     format.html { redirect_to cart_url(@cart), notice: "Added to cart" }
      #     format.json { render :show, status: :created, location: @cart }  
      #   else
      #     format.html { render :new, status: :unprocessable_entity }
      #     format.json { render json: @cart.errors, status: :unprocessable_entity }
      #   end
      # end 
    # else  
    #   puts "Cart already exists"  
    #   cart_qty = @cart[0]["QTY"] + prod_qty.to_i  
    #   @product = Product.find(params[:id])  
    #   @prod_total = @product.price * prod_qty.to_i  
    #   $cart_total = @cart[0]["TOTAL"] + @prod_total  
    #   Redis.current.set("cart_#{@cart[0]["ID"]}_total","#{@cart[0]["TOTAL"]}")  
    #   @a = @cart[0]["ITEMS"]
    #   @b = {  
    #       "product_id" => "#{@product.id}",  
    #       "product_name" => "#{@product.name}",  
    #       "product_qty" => "#{prod_qty.to_i}",  
    #       "product_total" => "#{@product.price * prod_qty.to_i}",  
    #       "retailer_id" => "#{Redis.current.get("retailer_id")}",  
    #       "status" => "false"  
    #   }.to_json
    #   @c = "#{@a}, #{@b}"
    #   client = Ignite::Client.new
    #   client.query("UPDATE PUBLIC.CARTS SET TOTAL=#{$cart_total}, QTY=#{cart_qty}, ITEMS='#{@c}';")
    #   # @cart.products = prod    
    #   # @cart.save
    #   puts "-=========PRODUCT IN CART AS: #{@cart[0]["ITEMS"]}==========-"
    #   # respond_to do |format|  
    #   #   if @cart.save  
    #   #     format.html { redirect_to cart_url(@cart), notice: "Added to cart" }
    #   #     format.json { render :show, status: :created, location: @cart }  
    #   #   else
    #   #     format.html { render :new, status: :unprocessable_entity }
    #   #     format.json { render json: @cart.errors, status: :unprocessable_entity }
    #   #   end
    #   # end   
    # end
  end
end



# DELETE /companies/id?/products/1 or /companies/id?/products/1.json
def destroy
  @product.destroy
  respond_to do |format|
    format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
    format.json { head :no_content }
  end
end
private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    # @product = Product.find(params[:id])
    client = Ignite::Client.new
    @product = client.query("SELECT * FROM PRODUCTS WHERE ID = #{params[:id]}")
    # @brand = Brand.find(@product.brand_id)
    @brand = client.query("SELECT * FROM BRANDS WHERE ID = #{@product[0]["BRAND_ID"]}")
    # @company = Company.find(@brand.company_id)
    @company = client.query("SELECT * FROM COMPANIES WHERE ID = #{@brand[0]["COMPANY_ID"]}")
    Redis.current.set("product_id","#{@product[0]["ID"]}")
    puts"========= REDIS SAVED PRODUCT ID #{Redis.current.get("product_id")} ========="
    Redis.current.set("company_id","#{@company[0]["ID"]}")
    puts"========= REDIS SAVED COMPANY ID #{Redis.current.get("company_id")} ========="
  end
  # Only allow a list of trusted parameters through.
  def product_params_image
    params.require(:product).permit(:name, :description, :price, :brand_id, :availability, :quantity, :subcategory , :image)
  end
  def product_params
    params.require(:product).permit(:name, :description, :price, :brand_id, :availability, :quantity, :subcategory)
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> unable to save this product:</h2>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>
  <div>
  <%= form.label :availability, style: "display: block" %>
  <%= form.select :availability, [["true", "true"], ["false", "false"]], selected: "Yes" %>
  </div>
  <div>
  <%= form.label :subcategory, style: "display: block" %>
  <%= form.select :category, [["Grocery", "Grocery"], ["Food", "Grocery"], ["Sports", "Grocery"],["Technology", "Grocery"]], selected: "Technology" %>
  </div>
  <div>
  <%= form.label :Photo, style: "display: block" %>
  <%= form.file_field :image %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<div>
  <%= link_to "Home", brands_path %>
   <%= link_to "Logout", "/" %>
</div>
<h1>Editing Product</h1>
<%= render "form", product: @product %>
<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Listing Products</h1> 
<p>
   <%# <%= link_to 'Search', search_posts_path %> Product
</p>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= product["NAME"] %></td>
    <td><%= product["DESCRIPTION"] %></td>
    <td><%= product["PRICE"] %></td>
    <td><%= link_to 'Show', product_path(product["ID"]) %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New product', new_product_path %>

app/views/products/index.json.erb
<%= sanitize collection.to_json %>

app/views/products/new.html.erb
<div>
  <%= link_to "Home", brands_path %>
   <%= link_to "Logout", "/" %>
</div>
<h1>New product</h1>
<%= render "form", product: @product %>
<br>
<div>
  <%= link_to "Back to Brands", brands_path %>
</div>

app/views/products/search.html.erb
<div>
  <%= link_to "Home", brands_path %>
   <%= link_to "Logout", "/" %>
</div>
<h1>Search Product</h1>
<%= form_for :search_products, url: search_products_path, method: :get do |form| %>
  <%= form.text_field :query, value: params[:search_products].presence && params[:search_products][:query] %>
  <%= form.submit 'Search' %>
<% end %>
<% unless @products.nil? %>
  <% if @products.empty? %>
    <h2>No products found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>
    <table style="width: 100%;">
      <thead>
         <tr>
           <th>Name</th>
           <th>Description</th>
           <th>Quantity Available</th>
           <th>Price</th>
         </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.quantity %></td>
            <td><%= product.price %></td>
            <td><%= link_to 'View', product_path(product.id) %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<% end %>

<div>
  <%= link_to "Back to Brands", brands_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= link_to "Home", categories_path %>
   <%= link_to "Logout", "/" %>
</div>
<%= render @product %>
<%= form_with(model: @product) do |form| %>
<div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
</div>
<div>
<%= image_tag("#{@url}", width: 180, heigth: 180) %>
</div>
  <div>
    <%= form.submit value="Add to Cart" %>
  </div>

<% end %>

app/views/products/show.json.erb
<%= sanitize resource.to_json %>